# Generated by Django 4.2.1 on 2023-05-19 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_datetime', models.DateTimeField(auto_now=True, verbose_name='Дата модификации')),
                ('code', models.CharField(verbose_name='code')),
            ],
            options={
                'verbose_name': 'Какие-то сущности',
            },
        ),
        migrations.CreateModel(
            name='SubjectApplicationCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_datetime', models.DateTimeField(auto_now=True, verbose_name='Дата модификации')),
                ('document_fields_in_type_doc', models.JSONField(verbose_name='Объект настроек')),
                ('link_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.subject', verbose_name='ID чего-то')),
            ],
            options={
                'verbose_name': 'Правила для каких-то правил',
            },
        ),
    ]
